name: fbl的博客
author: fengbaoli.com
#baseurl: /fengbaoli.com
keywords: test,github,git,jekyll,blog,jquery,flash,冯保丽
description: fbl的博客
github: https://github.com/ciciFbl
email: 2711584818@qq.com


encoding: utf-8
#highlighter: rouge
markdown: kramdown
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
